# Generated by Django 5.2.7 on 2025-10-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('florists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('flower_type', models.CharField(max_length=200)),
                ('flower_stylee', models.CharField(max_length=200)),
                ('seasonal', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='phots/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='phots/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField()),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='florists.florist')),
            ],
        ),
    ]
