# Generated by Django 5.2.7 on 2025-10-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flower_stylee',
            new_name='flower_style',
        ),
    ]
