# Generated by Django 5.2.7 on 2025-10-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_flower_stylee_product_flower_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
