# Generated by Django 5.2.7 on 2025-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0001_initial'),
        ('products', '0003_alter_product_photo_1_alter_product_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-title',)},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
    ]
