# Generated by Django 5.2.7 on 2025-10-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subject_product_category_product_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
