# Generated by Django 5.2.7 on 2025-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_occasion_product_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seasonal',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('New Year', 'New Year'), ('Chinese New Year', 'Chinese New Year'), ("Monther's Day", "Monther's Day"), ("Father's Day", "Father's Day"), ("Valentine's Day", "Valentine's Day"), ("Chinese Valentine's Day", "Chinese Valentine's Day"), ('Christmas', 'Christmas')], max_length=200),
        ),
    ]
